import { Aldrich, Poppins, Noto_Serif, Quantico} from "next/font/google";
import "./globals.css";

export const aldrich = Aldrich({
  subsets: ['latin'],
  weight: '400',

});

export const quantico = Quantico({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-quantico', 
});

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],

});

export const notoSerif = Noto_Serif({
  subsets: ['latin'],
  weight: ['400', '700'], 

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
