import { Geist, Geist_Mono, Aldrich, Poppins, Noto_Serif, Quantico} from "next/font/google";
import "./globals.css";

export const aldrich = Aldrich({
  subsets: ['latin'],
  weight: '400',

});

export const quantico = Quantico({
  subsets: ['latin'],
  weight: ['400', '700'], // Você pode colocar os pesos que quiser
  variable: '--font-quantico', // Nome da variável CSS
});

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],

});

export const notoSerif = Noto_Serif({
  subsets: ['latin'],
  weight: ['400', '700'], 

});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
